# Makefile for NuttX application
# 
# This is a simple Makefile for building NuttX applications

TOPDIR ?= $(CURDIR)
-include $(TOPDIR)/Make.defs

# Application directories
APPDIR = $(TOPDIR)

# Add application source files
ASRCS =
CSRCS = hello_main.c

include $(APPDIR)/Application.mk