name: Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            binary-suffix: ""
            archive-name: espbrew-macos-arm64.tar.gz
            server-archive-name: espbrew-server-macos-arm64.tar.gz
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary-suffix: ""
            archive-name: espbrew-linux-x86_64.tar.gz
            server-archive-name: espbrew-server-linux-x86_64.tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary-suffix: .exe
            archive-name: espbrew-windows-x86_64.zip
            server-archive-name: espbrew-server-windows-x86_64.zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev pkg-config

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Build binaries
      run: |
        cargo build --release --target ${{ matrix.target }} --bin espbrew
        cargo build --release --target ${{ matrix.target }} --bin espbrew-server

    - name: Create archives (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        mkdir -p artifacts
        
        # Create espbrew archive
        mkdir -p dist-espbrew
        cp target/${{ matrix.target }}/release/espbrew${{ matrix.binary-suffix }} dist-espbrew/
        cp README.md dist-espbrew/ 2>/dev/null || true
        cp LICENSE* dist-espbrew/ 2>/dev/null || true
        cd dist-espbrew
        tar czf ../artifacts/${{ matrix.archive-name }} *
        cd ..
        
        # Create espbrew-server archive
        mkdir -p dist-server
        cp target/${{ matrix.target }}/release/espbrew-server${{ matrix.binary-suffix }} dist-server/
        cp README.md dist-server/ 2>/dev/null || true
        cp LICENSE* dist-server/ 2>/dev/null || true
        cd dist-server
        tar czf ../artifacts/${{ matrix.server-archive-name }} *
      shell: bash

    - name: Create archives (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        New-Item -ItemType Directory -Force -Path artifacts
        
        # Create espbrew archive
        New-Item -ItemType Directory -Force -Path dist-espbrew
        Copy-Item "target/${{ matrix.target }}/release/espbrew${{ matrix.binary-suffix }}" -Destination "dist-espbrew/"
        if (Test-Path "README.md") { Copy-Item "README.md" -Destination "dist-espbrew/" }
        if (Test-Path "LICENSE*") { Copy-Item "LICENSE*" -Destination "dist-espbrew/" }
        Compress-Archive -Path "dist-espbrew/*" -DestinationPath "artifacts/${{ matrix.archive-name }}"
        
        # Create espbrew-server archive
        New-Item -ItemType Directory -Force -Path dist-server
        Copy-Item "target/${{ matrix.target }}/release/espbrew-server${{ matrix.binary-suffix }}" -Destination "dist-server/"
        if (Test-Path "README.md") { Copy-Item "README.md" -Destination "dist-server/" }
        if (Test-Path "LICENSE*") { Copy-Item "LICENSE*" -Destination "dist-server/" }
        Compress-Archive -Path "dist-server/*" -DestinationPath "artifacts/${{ matrix.server-archive-name }}"
      shell: powershell


    - name: Upload espbrew artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}-espbrew
        path: artifacts/${{ matrix.archive-name }}
        
    - name: Upload espbrew-server artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}-espbrew-server
        path: artifacts/${{ matrix.server-archive-name }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') && always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check build results
      run: |
        echo "Build job results:"
        echo "Build needs result: ${{ needs.build.result }}"
        if [[ "${{ needs.build.result }}" == "failure" ]]; then
          echo "⚠️ Some builds failed, but continuing with available artifacts"
        fi
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
      continue-on-error: true
        
    - name: Display structure of downloaded files
      run: |
        echo "Available artifacts:"
        ls -R artifacts/ || echo "No artifacts found"
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/**/*
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref, '-') }}
        body: |
          ## Installation
          
          ### One-line install (recommended):
          ```bash
          curl -L https://georgik.github.io/espbrew/install.sh | bash
          ```
          
          ### Manual download:
          Download the appropriate binaries for your platform from the assets below.
          
          ### Available Binaries:
          - **espbrew**: CLI tool for ESP32 project management
          - **espbrew-server**: Web server for browser-based project management
          
          ### Supported Platforms:
          - **macOS** (Apple Silicon): 
            - `espbrew-macos-arm64.tar.gz`
            - `espbrew-server-macos-arm64.tar.gz`
          - **Linux** (x86_64): 
            - `espbrew-linux-x86_64.tar.gz`
            - `espbrew-server-linux-x86_64.tar.gz`
          - **Windows** (x86_64): 
            - `espbrew-windows-x86_64.zip`
            - `espbrew-server-windows-x86_64.zip`
          
          ⚠️ **Note**: Some builds may have failed. Only successful builds are included in this release.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
